# Site settings
title: My Jekyll Website
description: A simple Jekyll website
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files and folders from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - api

# Custom variables
year: 2023
author: Leila Arstila
